name: Docker Cross-Platform Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: docker-compose build
    
    - name: Start Docker container
      run: docker-compose up -d
    
    - name: Wait for container startup
      run: sleep 120
    
    - name: Check container status
      run: docker-compose ps
    
    - name: Check container logs
      run: docker-compose logs
    
    - name: Run API health check
      run: |
        # Different curl command syntax for Windows
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          curl.exe -s http://localhost:5001/health || echo "API not responding"
        else
          curl -s http://localhost:5001/health || echo "API not responding"
        fi
    
    - name: Run Docker tests
      run: |
        # Run with bash on all platforms for consistency
        bash ./run_docker_tests.sh
    
    - name: Stop container
      run: docker-compose down 